### ISSUE TITLE
not support 1.9 on mobile ? 

### ISSUE THREAD

**Issue by pathtanan** [ThereforeGames/sd-webui-breadcrumbs#2]
update sd1.9 but the board disapear 
any fix

**Comment by ThereforeGames** [comment]
Hi @pathtanan,

The Breadcrumbs extension seems to be working fine on my mobile device. Some diagnostic questions:

- Are there any errors in your Python or browser console?
- Which mobile device are you using?
- Have you tried disabling your other extensions?

Thank you.

**Comment by pathtanan** [comment]
yes the button disapear 
i install friendly mobile extention is that coz ?

**Comment by pathtanan** [comment]
samsung galaxy s23 plus

**Comment by pathtanan** [comment]
ok t see problem thankyou
